export const siteConfig = {
  name: 'ZENTRYO',
  tagline: 'Industrial Engineering & Automation Solutions',
  description:
    'ZENTRYO is a trusted supplier of industrial components, automation systems, gas turbine spare parts, and OEM parts for power, oil & gas, and marine industries.',
  url: 'https://zentryo.in',
  ogImage: '/images/og-image.jpg',
  keywords: [
    'Industrial Automation',
    'Industrial Components',
    'Gas Turbine Spare Parts',
    'OEM Spare Parts',
    'Industrial Bearings',
    'Industrial Valves',
    'Industrial Manifolds',
    'Industrial Engineering',
    'Power Plant Equipment',
    'Automation Solutions',
    'Industrial Equipment Supplier',
    'Industrial Parts Supplier',
    'Energy Industry Components',
    'Oil and Gas Equipment',
    'PLC Components',
    'Industrial Sensors',
    'Automation Products',
    'Engineering Services',
    'Industrial Components Supplier India',
    'OEM Industrial Spare Parts Supplier',
    'Gas Turbine Spare Parts Supplier',
    'Automation Systems Supplier',
    'Industrial Bearings Distributor',
    'Power Plant Equipment Supplier',
  ],
  contact: {
    email: 'support@zentryo.in',
    contactEmail: 'contact@zentryo.in',
    phone: '+91 870-0198095',
    secondaryPhone: '+919718303073',
    address: '26/4, Okhla Phase 2, Ram Dulari Tundelkar Ji Road, Near Royal Enfield Showroom, Okhla Industrial Area, New Delhi, Delhi 110020, India',
    streetAddress: '26/4, Okhla Phase 2, Ram Dulari Tundelkar Ji Road, Near Royal Enfield Showroom, Okhla Industrial Area',
    locality: 'New Delhi',
    region: 'Delhi',
    postalCode: '110020',
    country: 'IN',
    coordinates: {
      lat: 28.5505,
      lng: 77.268,
    },
  },
  social: {
    linkedin: 'https://linkedin.com/company/zentryo',
    twitter: 'https://twitter.com/zentryo',
    facebook: 'https://facebook.com/zentryo',
    instagram: 'https://instagram.com/zentryo',
    youtube: 'https://youtube.com/@zentryo',
  },
  organization: {
    foundingDate: '2000',
    sameAs: [
      'https://linkedin.com/company/zentryo',
      'https://twitter.com/zentryo',
      'https://youtube.com/@zentryo',
      'https://facebook.com/zentryo',
    ],
  },
  productsPerPage: 24,
  productsPerPageGrid: 24,
  productsPerPageList: 12,
};

export type SiteConfig = typeof siteConfig;
